server:
  port: 8001

spring:
  application:
    name: hr-worker
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:hrworker_db
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2
  jpa:
    ddl-auto: update
    show-sql: true